Feature/category filter RTT 14
rohanBacancy/ReactCombinedTask pull request #5
Opened 2021-05-12 09:15 UTC by Harsh-asodariya

2021-05-12 11:33 UTC, vivek-bavishi requested changes

2021-05-12 11:33 UTC, vivek-bavishi commented on src/Component/category.tsx
> +    if (notes !== null) notesObj = JSON.parse(notes);
why
`if (notes !== null)`
are you provide?
instead of can we provide `if(notes)`

2021-05-12 11:33 UTC, vivek-bavishi commented on src/App.tsx
> +import "./App.css";
we follow to add imports of css or svg in after all components imports

2021-05-12 11:33 UTC, vivek-bavishi commented on src/Component/Select/select.tsx
> +}
we can use alphabetic order

2021-05-12 11:33 UTC, vivek-bavishi commented on src/Component/Select/select.tsx
> +}) => {
same alphabetic order we can follow

2021-05-12 11:33 UTC, vivek-bavishi commented on src/Container/notes.tsx
> +    if (notes !== null) setNotes(JSON.parse(notes));
same why ? you provide this condition instead of can use `if(notes)`

2021-05-12 13:06 UTC, Harsh-asodariya commented on src/Component/category.tsx
> +    if (notes !== null) notesObj = JSON.parse(notes);
resolves

2021-05-12 13:07 UTC, Harsh-asodariya commented on src/Component/Select/select.tsx
> +}
resolved

2021-05-12 13:07 UTC, Harsh-asodariya commented on src/Container/notes.tsx
> +    if (notes !== null) setNotes(JSON.parse(notes));
resolved

2021-05-13 12:26 UTC, Harsh-asodariya commented on src/Component/Select/select.tsx
> +}) => {
resolved

2021-05-13 12:26 UTC, Harsh-asodariya commented on src/App.tsx
> +import "./App.css";
resolved

2021-05-13 12:38 UTC, vivek-bavishi approved these changes

2021-05-13 12:38 UTC, merged